dist: focal

notifications:
  email:
    on_success: change
    on_failure: change

sudo: false
language: python
python:
  - "3.8"
  - "3.9"

install:
  - python3 -m pip install -U pip
  - python3 -m pip install -U build wheel tox tox-travis

script: tox
