dist: focal

notifications:
  email:
    on_success: change
    on_failure: change

sudo: false
language: python
python:
  - "3.8"
  - "3.9"

install:
  - pip --use-feature=in-tree-build install -U pip build wheel tox-travis

script: tox
